apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lolkek338
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: kovalka2017/first_chart
    argocd-image-updater.argoproj.io/first_chart.helm.image-name: image.name
    argocd-image-updater.argoproj.io/first_chart.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/first_chart.pull-secret: pullsecret:argocd/gcr-json-key
    argocd-image-updater.argoproj.io/first_chart.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds 

  finalizers:
    - resources-finalizer.argocd.argoproj.io
    
  labels:
    name: first_chart

spec:
  project: default

  source:
    chart: first_chart
    repoURL: https://github.com/kovalka2017/first_chart
    targetRevision: 0.1.0
    helm:
      values: |
          image:
            name: gcr.io/dynamic-circle-431306-h3/custom-nginx-helm-deployment-image
            tag: v0.1.37
    
  destination:
    server: https://kubernetes.default.svc  # if you want to deploy application in the same cluster where argocd server is running if thats diffrent then use cluster IP address.
    namespace: test

  syncPolicy:
    #syncOptions:
    #- CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
