apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
        imagePullPolicy: Always
        name: nginx-1
      - image: busybox:latest
        imagePullPolicy: Always
        name: busybox
        command:
        - sh
        - -c
        - echo Hello from BusyBox12345! && sleep 3600

